baseurl = "http://adele.im/"
languageCode = "en-fr"
defaultContentLanguage = "en-fr"
title = "Famille Adelé"
theme = "hugo-strata-theme"
disqusShortname = "hugo-strata-theme"
paginate = 7
canonifyurls = true

[permalinks]
  post = "/:year/:month/:slug/"

[taxonomies]
  tag = "tags"
  category = "categories"
  archive = "archives"

[author]
  name = "Bruno Adelé"
  bio = "passionné d’informatique depuis mon plus jeune âge, j’ai eu l’occasion de toucher les premiers ordinateurs individuels (Philips VG500, Amstrad CPC, Amiga, …), j’exerce toujours cette passion en entreprise depuis presque 20 ans"
  job = "Devops & Ingénieur Système"
  location = "Montpellier - France"
  # Your Gravatar email. Overwrite `author.picture` everywhere in the blog
  gravatarEmail = "bruno@adele.im"

  # Your profile picture
  # Overwritten by your gravatar image if `author.gravatarEmail` is filled
  picture = "https://cdn1.iconfinder.com/data/icons/ninja-things-1/1772/ninja-simple-512.png"
  # Your Twitter username without the @. E.g : thibaudlepretre
  twitter = "jesuislibre"
  # Your google plus profile id. E.g : +ThibaudLepretre or 114625208755123718311
  googlePlus = "+brunoadele"

# Menu Configuration
[[menu.main]]
  weight = 0
  identifier = "home"
  name = "Home"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-home\"></i>"
  url = "/"

[[menu.links]]
  weight = 0
  identifier = "github"
  name = "GitHub"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-github\"></i>"
  url = "https://github.com/kakawait"

[[menu.links]]
  weight = 1
  identifier = "stackoverflow"
  name = "Stack Overflow"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-stack-overflow\"></i>"
  url = "https://stackoverflow.com/users/636472/kakawait"

[[menu.misc]]
  weight = 0
  identifier = "rss"
  name = "RSS"
  pre = "<i class=\"sidebar-button-icon fa fa-lg fa-rss\"></i>"
  url = "/index.xml"

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Famille Adelé"
	description = "Bienvenue chez la famille Adelé"

	# Format dates with Go's time formatting
	date_format = "2016-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []


	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = ""
		# Use Markdown to format the string. This works nearly all over the theme
		bio = ""
		# The icons will be shown if you enter your username
		twitter = "jesuislibre"
		github = "badele"
		gitlab = ""
		dribbble = ""
		facebook = "bruno.adele"
		googleplus = "brunoadele"
		flickr = "b_adele"
		linkedin = "https://www.linkedin.com/in/brunoadele"

		copyright = [
			"&copy; [Bruno Adelé](//bruno.adele.im)",
			"Design: [Strata theme](//https://github.com/digitalcraftsman/hugo-strata-theme)",
		]


##############
# Adele custom
##############
[params.about]
    hide  = false
    title = "Bienvenue chez la famille Adelé"
    content = "Vous etes sur le site de la famille Adelé, veuillez cliquer sur la photo d'un membre de la famille pour allé sur son site blog"

[params.rss]
    hide = true

[params.avatar]
    hide = true

[params.contact]
    hide  = false
    title = "Contactez moi"
    content = "Utilisez ce formulaire pour me contacter"

    address = [
        "18 Rue fontaine de saint berthomieu",
        "Montpellier",
        "France"
    ]
    phone = "06.14.62.06.95"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    email = "bruno@adele.im"

    [params.contact.form]
        # Set custom strings for the form if your native
        # language isn't English
        name = "Prenom/Nom"
        email = "Email"
        message = "Message"
        submit = "Envoyer"


[params.portfolio]

        # The images and thumbnails are stored under static/images
        # Create and change subfolders as you like
        [[params.portfolio.gallery]]
            link = "http://bruno.adele.im"
            thumb = "thumb_bruno.jpg"
            title = "Bruno"
            description = "Né en 1972 à Alès, père de 2 enfants, passionné d'informatique depuis mon plus jeune âge, j'ai eu l'occasion de toucher les premiers ordinateurs individuels (Philips VG500, Amstrad CPC, Amiga, ...), j'exerce toujours cette passion en entreprise depuis presque 20 ans :) Mes principaux centre d'intérêt sont : </br><strong>Informatique</strong> => Virtualisation, Tunning/Benchmarking, Sécurité, OpenSource </br> <strong>Bricolage</strong> => Electronique, Domotique, Travail du bois </br><strong>Sport</strong> => Course à pied / trail"


        [[params.portfolio.gallery]]
            link = "http://adele.im"
            thumb = "thumb_steph.jpg"
            title = "Stephanie"
            description = "Née en 1976 à Beziers, j'ai grandi dans un petit village de l'Hérault de 200 habitants. Altruiste avant tout et passionnée par le service rendu au public. J'ai travaillé 11 ans au centre de documentation  d'un collège où j'ai pu partager ma passion des livres avec des adolescents. Je continue d'ailleurs de la transmettre, cette fois ci aux plus 'grands' car je travaille depuis 2014 dans les bibliothèques universitaires. Mes meilleurs souvenirs d'enfance : lorsque le bibliobus venait sur la place du village pour nous permettre de choisisr des livres pour la classe et nous faire découvrir la magie de la lecture."

        [[params.portfolio.gallery]]
            link = "http://adele.im"
            thumb = "thumb_lucas.jpg"
            title = "Lucas"
            description = "Né en 2003 à Montpellier. Prend le chemin du Geek, peut  être un peu trop ?"

        [[params.portfolio.gallery]]
            link = "http://adele.im"
            thumb = "thumb_lou.jpg"
            title = "Lou"
            description = "Né en 2007 à Montpellier. Cherche la moindre occasion pour s'évader"
